name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        cargo install cargo-generate \
        && cargo generate https://github.com/pierwill/pest-template --name test \
        && cd test/ \
        && cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
